Fix memory leak issues reported by valgrind
Fixed invalid memory read errors due to accessing
previously freed address spaces.

Also, fixed an unintialised variable usage error.

data.c: In function ‘sch_xpath_to_gnode’:
data.c:1433:12: error: ‘node’ may be used uninitialized in this function
[-Werror=maybe-uninitialized]
 1433 |     return node;
      |            ^~~~
cc1: all warnings being treated as errors
make: *** [Makefile:512: apteryx_netconf-data.o] Error 1